### Standard: Valid -> true
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "this is my first chirpy b"
}

### Missing Body: error reflects that
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

### Too long
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "this is my first chirpy bthis is my first chirpy bthis is my first chirpy bthis is my first chirpy bthis is my first chirpy bthis is my first chirpy bthis is my first chirpy bthis is my first chirpy b"
}

### Extra
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "this is my first chirpy bthis is my first chirpy bthi",
    "extra": "this should be ignored"
}

### Bad words
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "body": "this is my kerfuffle sharbert fornax first chirpy bthis is my first chirpy bthi",
}




